export const infoData = [
    {title : 'Personal Information', description : 'We collect personal details such as your name, email address, phone number, and payment information during registration or usage of our services.'},
    {title : 'Non-Personal Information', description : 'We may collect non-identifiable data such as device type, operating system, and user behavior for analytical purposes.'}, 
];
export const infoUse = [
    {title : 'Account Setup and Authentication', description : 'To register and authenticate your account.'},
    {title : 'Service Delivery', description : 'To connect users with service providers and facilitate secure and efficient communication.'},
    {title : 'Improvement and Personalization', description : 'To enhance user experience through tailored features and updates'},
    {title : 'Communication', description : 'To send essential updates, service notifications, and promotional material (with the option to opt out).'},
]

export const securityData = [
    {title : 'No Unauthorized Sharing', description : 'We do not share personal data with third parties for marketing or other purposes without your explicit consent'},
    {title : 'Service Providers', description : 'Basic information may be shared with authorized service providers to facilitate services.'},
    {title : 'Legal Compliance', description : 'We may disclose data to comply with legal obligations or prevent fraud, unauthorized activity, or harm.'},
    {title : 'Encryption', description : 'All user data is encrypted and stored securely to prevent unauthorized access.'},
    {title : 'Limited Access', description : 'Only authorized personnel with strict confidentiality agreements can access minimal data necessary for service delivery.'},
]

export const paymentData = [
    {title : 'What We Process', description : 'For financial transactions, we process payment account details, transaction amounts, and relevant identifiers.'},
    {title : 'What We Don’t Retain', description : 'We do not store sensitive payment information such as card numbers, PINs, or UPI credentials.'},
    {title : 'Third-Party Processors', description : 'Payments are processed through secure, third-party providers adhering to industry standards.'},

]

export const rightsData = [
    {title : 'Access and Correction', description : 'You can view or update your personal details via your account settings'},
    {title : 'Data Deletion', description : 'You may request account deletion or data removal through our support channels.'},
   
]

export const tncData = ["A.	This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
   "B.	This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://talkmatezapp.com (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).",
   `C.	The Platform is owned by Talkmatez Pvt Ltd, a company incorporated under the Companies Act, 1956 with its registered office at 4/381 Ground floor Muppatta Kunnummal, Ekarool, Unnikulam, Calicut 673574, India (hereinafter referred to as "Platform Owner", “we”, “us”, “our”).`,
   `D.	Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.`,
    `E.	For the purpose of these Terms of Use, wherever the context so requires "you", “your” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.`,
    `F.	ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING`,
    `G.	The use of Platform and/or availing of our Services is subject to the following Terms of Use`,
    `I.	To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.`,
    `II.	Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. ensure that the Services meet your requirements.`,
    `III.	Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and `,
    `IV.	The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.`,
    `V.	You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.`,
    `VI.	You agree to pay us the charges associated with availing the Services.`,
    `VII.	You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.`,
    `VIII.	You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.`,
    `IX.	You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.`,
    `X.	You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.`,
    `XI.	In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less`,
    `XII.	Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.`,
    `XIII.	These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.`,
    `XIV.	All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Calicut Keral`,
    `XV.	All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.`,

]

export const refundData = [
    `(i)	Cancellations will only be considered if the request is made 2 days of placing the order. However, cancellation request may not be entertained if the orders have been communicated to such sellers / merchant(s) listed on the Platform and they have initiated the process of shipping them, or the product is out for delivery. In such an even, you may choose to reject the product at the doorstep.`,
    `(ii)	Talkmatez does not accept cancellation requests for perishable items like flowers, eatables, etc. However, the refund / replacement can be made if the user establishes that quality of the product delivered is not good.`,
    `(iii)	In case of receipt of damaged or defective items, please report to our customer service team. The request would be entertained once the seller/ merchant listed on the Platform, has checked and determined the same at its own end. This should be reported within 2 days of receipt of products. In case you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 2 days of receiving the product. The customer service team after looking into your complaint will take an appropriate decision. `,
    `(iv)	In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.`,
    `(iv)	In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.`,
    
]

